baseurl = "http://celestialli.github.io"
title = "Anton's Homepage"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Anton"
  info = "AI and Software Engineer"
  description = "Anton's Blog"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "real.celestialli@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/celestialli/"
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/shuqiaoli/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"